version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: toolhub-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: toolhub-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env

